language: python
sudo: false

python:
    - "2.7"
  
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - wget https://github.com/alexdobin/STAR/archive/STAR_2.5.2a.tar.gz
  - tar -xzf STAR_2.5.2a.tar.gz
  - cd STAR_2.5.2a
  - make STAR
  - cp STAR $HOME/miniconda/bin

install:
    - conda create -q -n testenv --yes python=2.7 numpy scipy pandas
    - source activate testenv
    - python setup.py install
   
script:
    - python setup.py test

notifications:
    email: false
